# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
  desc "Push a new release to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "6KV3Q77DCF",
      issuer_id: "9712599d-e1b5-4d1b-940b-4503cabf4b10",
      key_filepath: "./fastlane/AuthKey_6KV3Q77DCF.p8",
      in_house: false,
    )

    # Increment the build number
    increment_build_number

    # Build the app
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.emf.mealmate": "mealmatedev.mobileprovision",
        }
      }
    )

    # Upload the build to TestFlight
    upload_to_testflight(api_key: api_key)
  end
end
